#!/bin/sh -ex

CONFFILE1="/usr/share/zabbix-agent/zabbix_agentd.conf"
CONFFILE_DEST1="/etc/zabbix/zabbix_agentd.conf"

. /usr/share/debconf/confmodule
db_version 2.0 || [ $? -lt 30 ]

if [ "$1" = "configure" ]; then

    RET=""
    db_get zabbix-agent/server || true
    zabbix_server="$RET"
    if [ "$zabbix_server" = "" ]; then
        zabbix_server="localhost"
    fi

    sed "s/^[# ]*Server=.*/Server=$zabbix_server/g" < $CONFFILE1 > $CONFFILE_DEST1.new 
    ucf --debconf-ok $CONFFILE_DEST1.new $CONFFILE_DEST1
    rm -f $CONFFILE_DEST1.new

    if ! getent group zabbix > /dev/null 2>&1 ; then
    addgroup --system --quiet zabbix
    fi

    # Does the user 'zabbix' exist?
    if ! getent passwd zabbix > /dev/null 2>&1 ; then
        # Not yet. Create it.
        adduser --quiet \
            --system --disabled-login --ingroup zabbix \
            --home /var/run/zabbix/ --no-create-home \
            zabbix
    else
        # Yes, user 'zabbix' exists. 
        # Change the home directory from /var/run/zabbix-server 
        # to /var/run/zabbix (relates to bug #593458).
        # Check current home directory of the 'zabbix' user.
        getent passwd zabbix | cut -d: -f6 | grep -q /var/run/zabbix-server
        if [ $? -eq 0 ]; then
            # Home directory is still the old /var/run/zabbix-server directory.
            # All processes run by the 'zabbix' user must be stopped
            # before usermod can change the home directory.
            for component in server proxy agent; do
                #if [ -e /etc/init.d/zabbix-$component ]; then
                #    /etc/init.d/zabbix-$component stop
                #fi
                invoke-rc.d zabbix-$component stop
            done
            # Remove an existing /var/run/zabbix directory just in case
            rm -rf /var/run/zabbix
            # Move the home directory
            usermod -m -d /var/run/zabbix zabbix
            # Start the processes again
            for component in server proxy agent; do
                #if [ -e /etc/init.d/zabbix-$component ]; then
                #    /etc/init.d/zabbix-$component start
                #fi
                invoke-rc.d zabbix-$component start
            done
        fi
    fi
    chown zabbix:zabbix /var/log/zabbix-agent -R
fi

db_stop

#DEBHELPER#

exit 0
